cpp-best-practices/cpp_starter_project

CMakeLists.txt
I prefer to use target_compile_options instead of add_compile_options (or any target_* instead of global commands) as it doesn't "pollute" the global environment. While I think of it of a good practice, there are some downsides too, and will try to enumerate both pros and cons here : 
* Does not pollute the rest of the environment, hence allowing the integration of external dependencies (or existing code) using add_subdirectory
* In a more general way, flags should be set by target : 
- sometimes you might want high level of warnings, perhaps even warning as error, sometimes you simply can't and need to disable some.
- It might not make sense to add flags to all targets, for example (not the best one, but still) you might want to build without exceptions and use -fno-exceptions, but then …
=> Use target_compile_options and interface library

CMakeLists.txt, qt/CMakeLists.txt, qt/HelloQt.cpp, qt/HelloQt.hpp, qt/qtMain.cpp
Updated using the recommendations from @alexallmont.
Remarks:
I haven't run clang-format on the code. The options that are in the .clang-format file are too new for my clang-format-3.5
You should really update your CMake Required version to 3.8, that is when cxx_std_17 makes it into target_compile_features, otherwise use the features you are actually using.
CMakeLists separated into subdirectory as suggested, I also took the liberty of adding some CMake define options so that I could actually run CMake without installing gtk.
=> Add qt gui

CMakeLists.txt
The usage of options as it was implemented didn't work. Even though specifying that I only want to build the GTKMM GUI, CMake complained that it couldn't find some of the other toolkits.
Digging into the usage of options in the main CMakeLists.txt I found that they are not used properly.
This PR should fix those issues.
=> Fix use of cmake options

CMakeLists.txt
In modern CMake it is preferable to link against other targets rather
than to add include paths and libraries of dependencies manually (see
https://www.youtube.com/watch?v=P4Rzd21U-1c)
Since CMake 3.6, the functions `pkg_check_modules` and
`pkg_search_module` of CMake module `FindPkgConfig.cmake` provide
`IMPORTED_TARGETS` to support this new paradigm.
=> CMake: Use IMPORTED_TARGET for dependencies found via pkg_check_modules

.github/workflows/build_cmake.yml
I've managed to add Github Actions CI basic workflow for ubuntu. It's currently limited to linux platform, but I think it's a nice addition and maybe later we will manage to use all platforms supported by Github Actions?
=> Add Github Actions CI workflow

.travis.yml, appveyor.yml, cmake/CompilerWarnings.cmake, cmake/Conan.cmake, cmake/Sanitizers.cmake, test/CMakeLists.txt
There are a lot of people hanging out in the issues section that are having trouble getting this project to build properly on a Mac. For this reason, I think that it's really important to get continuous integration going on the Mac side. This will prevent a lot of headaches for Mac users.
=> Add a working Mac CI build

cmake/CompilerWarnings.cmake
Added flag for standards conforming code in CompilerWarnings on Windows MSVC builds.
=> Update CompilerWarnings to include permissive-

.cmake-format.yaml
Since version 0.6.0 (Oct. 2019) cmake-format's `max-subargs_per_line`
option is removed. Similar behavior is achieved with `max_pargs_hwrap`.
=> Upgrade cmake-format

cmake/Sanitizers.cmake
The function param is used when setting sanitizers but not when setting coverage check.
=> Don't hardcode the target name when setting coverage check

CMakeLists.txt
Before, ENABLE_FUZZING was not listed in ccmake.
=> add ENABLE_FUZZING to options

cmake/StaticAnalyzers.cmake, fuzz_test/fuzz_tester.cpp
Ignore cppcheck warning 'unusedFunction' for `LLVMFuzzerTestOneInput`.
To enable inline suppression the option `--inline-suppr` has to be added
to the cppcheck invocation (cmake/StaticAnalyzers.cmake).
=> ignore unusedFunction for LLVMFuzzerTestOneInput

cmake/Conan.cmake
spdlog 1.5 and 1.6 now require fmt 6.2.0, as of this commit:
https://github.com/conan-io/conan-center-index/pull/1651/commits/c19230f8ad6ae31a3699c4a66d90e29bad502ecb
=> Fix spdlog dependency warning

README.md
Closes #66. VS2017 doesn't work with catch2, but VS2019 works just fine.
=> Update README to recommend VS2019

.travis.yml
The xcode11.2 MacOS image on Travis does not include a `/usr/bin/gcov-9`
executable, which causes the codecov script to silently fail. I'm not
sure why it doesn't cause the whole build to fail.
This code looks like it works, but it doesn't, and that's a problem.
Even if this code did work, I don't think we really want it, because
we already have a working codecov script running on the Linux gcc build.
I don't think it makes sense to generate a duplicate report.
=> Don't call non-existent gcov on MacOS

.travis.yml, appveyor.yml
When Conan version 2.0 is released, it will require Python 3 to run. When that happens, this project's CI builds may break when Conan runs using Python 2.
This calls `python3` directly to install Conan globally; this ensures that Conan is available to CMake, and it will always be run with Python 3. 
* An alternate and much simpler solution would be to use more recent images of Ubuntu and MacOS that use Python 3 as the default version of Python, for instance, Ubuntu 20.04. I am hesitant to recommend this solution because it breaks compatibility with older versions of Ubuntu and Mac.
* Another possibility would be update-alternatives, which is a great way to manage different versions of programs on Ubuntu. To my knowledge, it doesn't exist on Mac.
* Travis appears to use pyenv to set the …
=> Use python3 instead of python2 in CI

README.md
This extra flag commands vswhere to include any product, including VC build tools, in the search. People might not install a full Visual Studio, and this adds support for that.
=> Fix adding compilers to Windows PATH during installation

.github/workflows/build_cmake.yml
This caches Conan built packages in GitHub Actions. This results in a much shorter `cmake configure` time since the dependencies are not downloaded and built every time from the scratch.
This uses `${{ runner.os }}-${{ env.BUILD_TYPE }}-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('cmake/Conan.cmake') }}` as its key for the cache restore which means changing the variables (such as BULD_TYPE) will result in downloading and building from the scratch.
Successful run: 
https://github.com/aminya/cpp_starter_project/actions/runs/278519004
As you see configure only takes 3s.
=> Cache Conan built packages in GitHub Actions

CMakeLists.txt
Hello,
I've been playing around a bit with your `cpp_starter_project` and I think I found an issue with how the `-ftime-trace` option is being registered into the project. It seems I've also find a solution, but could you please take a look at it as I'm fairly new to CMake. Thanks in advance.
Cheers,
PETR
=> Fixed -ftime-trace option registration command

src/fltk/CMakeLists.txt, src/gtkmm/CMakeLists.txt
Removed the folder prefix in the add_executable cmake command in src/fltk/CMakeLists.txt and src/gtkmm/CMakeLists.txt to fix the following error that occures during CMake Generation:
`CMake Error at src/fltk/CMakeLists.txt:2 (add_executable):
Cannot find source file:
fltk/test_fltk.cpp
Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
.hpp .hxx .in .txx
CMake Error at src/gtkmm/CMakeLists.txt:7 (add_executable):
Cannot find source file:
gtkmm/main.cpp
Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
.hpp .hxx .in .txx
CMake Error at src/fltk/CMakeLists.txt:2 (add_executable):
No SOURCES given to target: test_fltk
CMake Error at src/gtkmm/CMakeLists.txt:7 (add_executable):
No SOURCES given to target: test_gtkmm
`
=> Fix CMakeLists.txt on src/fltk and src/gtkmm

.clang-tidy
Disable llvmlibc-callee-namespace warnings. This case was not covered due to the second dash.
=> Disable llvmlibc-callee-namespace warnings

src/main.cpp
Removes the duplicate "#include \<iostream\>". Unless this is for demonstrating warnings/static analysis. Though the default static analysis tools didn't pick it up.
=> Remove duplicate header in template source file

cmake/Conan.cmake
At some point, spdlog 1.5.0 changed its dependencies to require fmt 6.2.1, rather than 6.2.0. As a result, every time you configure the project, you see this warning:
WARN: spdlog/1.5.0: requirement fmt/6.2.1 overridden by your conanfile to fmt/6.2.0
This commit fixes that warning, and prevents whatever latent bugs the spdlog devs expect this version mismatch to cause.
Note that the current version of spdlog (1.8.2) requires fmt version 7.1.3; it would make a lot of sense to update the versions of both packages.
=> Fix Conan warning for spdlog dependency

.lgtm.yml, README.md, cmake/Conan.cmake
The [lgtm](https://lgtm.com/) vulnerability analysis tool does not work with out-of-tree builds without a custom extraction config. This PR proposal adds the required config and badge.
N.B. the badge status will only show-up after being merged. For illustration, you may consult [this](https://github.com/fair-acc/opencmw-cpp) as an example). In addition, we also added the missing conan-center repository (needed for catch2), bumped the conan-cmake plugin and fmt version number (both caused needles conflict/warning messages).
Thanks also to my fellow co-conspirator @wirew0rm.
=> Add config and badge for lgtm vulnerability analysis tool

cmake/Conan.cmake
This PR is a partial duplicate of (now closed) #139. Thank you to @arvidsaur for their initial PR.
* The old bincrafters remote was shutdown on 2021-05-01, as described in [this](https://bincrafters.github.io/2020/04/19/infrastructure-changes-and-required-actions/) post. 
* All packages were moved to a new remote, link to which I added to `cmake/Conan.cmake`. 
* The new remote requires Conan's [package revisions](https://docs.conan.io/en/latest/versioning/revisions.html) to be on, best way of doing this (that I found),without requiring users to change their global `conan.conf` is  by setting the environment variable `CONAN_REVISIONS_ENABLED=1` with cmake.
Edit: Added missing closing bracket..
=> Updated bincrafters' remote link and using conan package revisions 

cmake/CompilerWarnings.cmake
Clang doesn't enable this warning by default neither in `-Wall` nor `-Wextra`.
=> Add `-Wimplicit-fallthrough` to Clang warnings

.travis.yml, cmake/CompilerWarnings.cmake, cmake/Sanitizers.cmake, cmake/StandardProjectSettings.cmake
while CMake options are mostly syntactic sugar for cached boolean
variables which support both ON/OFF and TRUE/FALSE, they are documented
with ON/OFF exclusively (https://cmake.org/cmake/help/latest/command/option.html).
ON/OFF were also used elsewhere in the project, so this commit makes the
use consistent throughout the project.
=> use ON/OFF consistently for CMake options

cmake/Sanitizers.cmake
when clang is invoked with -fsanitize=memory, all libraries, including the standard library has to be built with that instrumentation to avoid false positives. This PR emits a warning for that case, so people do not have to google for the reason for failing CMake builds
https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo
=> warn about need for instrumented libs with MSan when using clang

test/constexpr_tests.cpp, test/tests.cpp
- Factorial is explicitly implemented recursively, so we'll have to
explicitly disable the check for recursive function calls here
(failure found with clang-tidy-12)
=> disable clang-tidy failure on recursive function

src/nana/CMakeLists.txt
Currently, the Nana example does not compile when `WARNINGS_AS_ERRORS` is turned on. This is because there are shadowed variable names in the Nana header file, which triggers the `-Wshadow` warning. This change convinces the compiler not to trigger warnings on any of the Nana headers. With this fix applied, you don't get errors from the Nana headers, but you still get the benefits of `WARNINGS_AS_ERRORS` in your own code.
This change adds the `SYSTEM` keyword to the `target_include_directories` call that adds the Nana headers. This will convince the compiler that the Nana headers are system headers, and should not be affected by warnings. 
See `target_include_directories` docs at: https://cmake.org/cmake/help/v3.0/command/target_include_directories.html
=> Fix compilation failure for Nana example

src/main.cpp
I had no prior experience with docopt, the default output would have been more clear by expressing the pair as key=value rather than keyvalue.
=> docopt default output

cmake/Conan.cmake
Trying to build the the project from scratch (on my Windows machine with VS2019 open folder functionality) it failed to download catch2/2/11/0. After a bit of search I realized that this version of catch2 is on conan-center repo and I didn't added that one before. Conan.cmake should add all necessary conan repos you need.
P.S. there is a new catch2/2/13.3 version but I am not sure how regularly this template project should update the third party libraries.
=> Add conan-center repo to be able to find missing packages (e.g. catch2)

README.md
* adjusted link to the new organization name.
* shuffled and aligned the badges to fit on a line to be a bit more concise.
Some badges (Travis etc) still refer to the 'lefticus' reference. I presume the build system/other GH integrations aren't updated to the new name yet.
=> updated lgtm badge link and shuffled badge order

fuzz_test/CMakeLists.txt
Since #150, we have moved away from the `CONAN_PKG` style of including packages, which helps decouple this project from Conan. There was one last `CONAN_PKG` usage hiding in `fuzz_test/CMakeLists.txt`; this fixes that.
It looks like no one tried to run the fuzz test since #150. Perhaps this target should be included in the CI tests?
=> Remove the last instance of CONAN_PKG

cmake/StaticAnalyzers.cmake
Fix #140.
It is possible that we will need to pass paths into the ‘-i’ option, as mentioned in https://github.com/cpp-best-practices/cpp_starter_project/issues/140#issuecomment-842090362. But until then, YAGNI, so I did not implement it.
=> Remove imgui reference in `StaticAnalysis.cmake`

CMakeLists.txt
Includes two emergency bugs:
https://github.com/cpp-best-practices/project_options/releases/tag/v0.13.1
=> fix: update project_options

.github/workflows/ci.yml, .lgtm.yml, test/CMakeLists.txt
* Need to make sure opt_enable_coverage is set when appropriate (only for Debug builds, since it overrides optimization settings)
* Remove explicit sources dir from windows coverage, so that it still works when template project is used
* Make sure gcov version/executable is set correctly
* Add simple test of main executable, to show its coverage also
Note: these issues were discovered while using a recent project made from the template. I think most of these issues are long standing. Previously `ENABLE_COVERAGE` was enabled by default, so it happened to work, but Release builds were not doing what we thought they were doing.
=> Fix coverage reporting
